export const hotelTypes = [
  "Luxury Apartment",
  "Workation apartment ",
  "Hill view apartment ",
  "Sunrise Apartment ",
  "Hill View Condo",
  "Family Apartment ",
  "Luxury Apartment ",
  "Mountain View Condo",
  "Mountain View Flat",
  "Sunlit Apartment ",
  "Studio Apartment ",
  "Spacious Studio Apartment",
  "Pet Friendly",
];

export const hotelFacilities = [
  "Private Living and Dining Space",
  "OTT Subscribed Smart TV",
  "Private Washing Machine",
  "Free On site Shared Parking Space",
  "24X7 Security Guard",
  "Elevator",
  "High Speed Internet WiFi",
  "Power Back up by Inverter",
  "Support in Check-in & Check-out",
  "Bath Towels",
  "Shampoo and Bath Soap",
  "Hot Water",
  "Wardrobe",
  "On demand Iron",
  "Hair Dryer",
  "Air-conditioned bedroom",
  "PTC heater in bedroom",
  "Fully Functional Kitchen",
  "Water Purifier",
  "Microwave",
  "Toaster",
  "Refrigerator",
  "Chimney",
];
