export const reviews = [
  "Everything was lovely. I felt at home and the hosts were kind. Thank you Yogvan! I will be back!",
  "This property is like home away home. Nicely maintained and everything is in place . Staff very cooperative. Very spacious flat .",
  "Nice and clean , took a bit of time to work out how the hot water tank works.",
  "A very well maintained place, nice and helpful host, it's truly a home away from home.",
  "1.Very clean apartment with each and everything in place. 2.In every aspect the apartment exceeded my expectations. 3. I think it is in some ways better than my home. 4.",
  "it was clean and comfy.perfect for family of 4-5. all the needy things were available in kitchen.",
  "The stay was super comfortable and awesome. There was quick response to any query and immediate solutions. We had a wonderful time. 😊",
  "The appartment is great. Clean, cozy and complete. The staff responds quickly. The old man at the parking is really sweet.",
  "Location is great. The host was constantly in touch to make sure our stay was comfortable. The kitchen was functional. Bathrooms were clean.",
  "Very decent apartment with all household facilities. Maintenance was good. Clean and Tidy.",
  "Absolutely wonderful experience! The ambiance was so cozy, and the staff was incredibly helpful. Can't wait to come back again!",
  "This property exceeded all expectations. From the cleanliness to the spaciousness, everything was top-notch. Highly recommend!",
  "Had a fantastic stay here. The attention to detail was impressive, and the host went above and beyond to make us feel welcome.",
  "Great location, impeccable cleanliness, and outstanding service. Will definitely be returning in the future!",
  "I was blown away by how well-maintained this place was. Truly felt like a home away from home. Kudos to the management!",
  "The perfect retreat for a family getaway. The amenities provided were excellent, and the atmosphere was so relaxing.",
  "From check-in to check-out, everything was seamless. The staff was incredibly attentive, and the facilities were pristine.",
  "Highly recommend this property to anyone looking for a comfortable and enjoyable stay. A+ all around!",
  "Had an amazing time here. The attention to detail was evident everywhere, and the staff couldn't have been more accommodating.",
  "A hidden gem! The location was fantastic, and the apartment itself was modern and well-equipped. Can't wait to return!",
  "Fantastic experience! The room was immaculate and the view from the balcony was breathtaking. The staff went above and beyond to ensure our comfort.",
  "I can't say enough good things about this place. The decor was stylish, the bed was comfortable, and the location was perfect. Will definitely be returning!",
  "Had a wonderful stay at this property. The owner was incredibly friendly and provided great recommendations for local restaurants and attractions.",
  "The property exceeded our expectations in every way. The pool area was beautiful, the rooms were spacious and clean, and the breakfast buffet was delicious.",
  "Absolutely loved our time here. The attention to detail was evident throughout the property, and the staff were always friendly and attentive.",
  "This hotel is a hidden gem! The ambiance was charming, the service was impeccable, and the complimentary snacks in the room were a nice touch.",
  "We had a fantastic stay at this property. The location was perfect for exploring the city, and the room was modern and well-appointed.",
  "Highly recommend staying here. The check-in process was seamless, the room was spotless, and the complimentary breakfast was a nice added bonus.",
  "We couldn't have asked for a better experience. The property was beautiful, the staff were friendly and helpful, and the amenities were top-notch.",
  "10/10 would stay here again. The property had everything we needed for a comfortable stay, and the staff went out of their way to ensure we had a great time.",
  "The hotel exceeded my expectations. The room was clean, spacious, and well-furnished. The staff was courteous and attentive to our needs.",
  "I had a wonderful experience staying at this property. The location was convenient, and the amenities provided were excellent. I would highly recommend it to others.",
  "We thoroughly enjoyed our stay here. The atmosphere was serene, and the surroundings were beautiful. It was a perfect getaway from the hustle and bustle of city life.",
  "The service was impeccable from start to finish. The staff went above and beyond to ensure our comfort and satisfaction. We will definitely be returning guests.",
  "I cannot praise this hotel enough. The attention to detail in every aspect of our stay was remarkable. It truly felt like a home away from home.",
  "The cleanliness of the room and facilities was top-notch. We felt safe and comfortable throughout our stay. Thank you to the management and staff for their hospitality.",
  "I was impressed by the variety and quality of amenities offered at this property. From the fitness center to the pool area, everything was well-maintained and enjoyable.",
  "The check-in process was smooth, and the front desk staff were welcoming and helpful. Any questions or concerns we had were addressed promptly. Overall, a fantastic experience.",
  "We had a fantastic time exploring the local area, and the hotel's convenient location made it easy to access nearby attractions. We will definitely be back for another visit.",
  "The complimentary breakfast provided was delicious and offered a wide selection of options. It was a great way to start each day of our stay.",
  "Our stay at this property was nothing short of amazing. The attention to detail in the room decor and amenities was impressive. We felt pampered throughout our visit.",
  "The views from our room were breathtaking. Waking up to such stunning scenery made our stay truly unforgettable. We couldn't have asked for a better experience.",
  "I was pleasantly surprised by the level of eco-friendliness practiced at this hotel. It's refreshing to see a property that prioritizes sustainability without compromising on comfort.",
  "The staff's professionalism and friendliness left a lasting impression on us. They were always willing to go the extra mile to ensure our needs were met. Kudos to the entire team!",
  "As frequent travelers, we've stayed in many hotels, but this one stands out for its exceptional service and attention to detail. It's clear that guest satisfaction is their top priority.",
  "The concierge service was incredibly helpful in providing recommendations for local attractions and dining options. Their insights helped us make the most of our time in the area.",
  "From the moment we arrived, we were greeted with warmth and hospitality. It felt like we were welcomed into a family rather than just checking into a hotel. Such a wonderful experience!",
  "The property's ambiance was so inviting and relaxing. It provided the perfect retreat after a long day of exploring. We found ourselves eagerly looking forward to returning to our room each evening.",
  "We appreciated the little touches throughout our stay, like the complimentary evening snacks and turndown service. It's these thoughtful gestures that set this property apart from the rest.",
  "I can't say enough good things about this hotel. From the luxurious bedding to the state-of-the-art facilities, every aspect of our stay exceeded our expectations. We will definitely be back!",
  "This property truly went above and beyond to make our anniversary getaway special. The personalized touches and attention to detail made us feel like valued guests.",
  "From the moment we stepped into the lobby, we were greeted with a sense of tranquility. It's rare to find a hotel that combines luxury with such a peaceful atmosphere.",
  "We were impressed by the variety of dining options available onsite. Whether we were craving fine dining or a casual meal, there was something to satisfy every palate.",
  "The room upgrade we received upon check-in was a pleasant surprise. It added an extra layer of luxury to our stay and made us feel truly valued as guests.",
  "The attention to cleanliness and hygiene throughout the property was commendable. We felt safe and secure knowing that every precaution was being taken to ensure our well-being.",
  "The hotel's commitment to sustainability was evident in every aspect of our stay, from the eco-friendly toiletries to the energy-efficient lighting. It's reassuring to see a property that cares about the environment.",
  "We were blown away by the breathtaking views from our balcony. It was the perfect spot to enjoy a morning coffee or unwind with a glass of wine in the evening.",
  "The complimentary shuttle service to nearby attractions was a convenient perk that made exploring the area hassle-free. It was a thoughtful gesture that added value to our stay.",
  "Overall, our experience at this property exceeded our expectations in every way. From the warm hospitality to the luxurious amenities, it was a truly unforgettable stay.",
  "We had a wonderful time staying at this property. The staff were incredibly accommodating and went out of their way to ensure our comfort. We couldn't have asked for better service.",
  "The design and decor of the hotel were exquisite. Every corner seemed to be thoughtfully curated, creating a truly luxurious atmosphere.",
  "The amenities provided exceeded our expectations. From the heated pool to the well-equipped gym, there was something for everyone to enjoy.",
  "The breakfast buffet was a highlight of our stay. The selection was extensive, and the quality of the food was outstanding. It was the perfect way to start each day.",
  "The location of the property was ideal for exploring the surrounding area. We were able to easily access nearby attractions and restaurants, making our stay even more enjoyable.",
  "We were impressed by the level of attention to detail throughout the property. It was clear that every aspect of our stay had been carefully considered, resulting in a seamless and enjoyable experience.",
  "The in-room amenities were top-notch. From the plush bathrobes to the high-quality toiletries, we felt pampered from the moment we arrived.",
  "The hotel's commitment to customer satisfaction was evident in every interaction we had with the staff. They went above and beyond to ensure that our needs were met and that we had a memorable stay.",
  "The room was spacious and beautifully appointed, providing a comfortable retreat after a long day of sightseeing. We appreciated the extra touches, like the complimentary bottle of wine waiting for us upon arrival.",
  "Overall, we couldn't fault our experience at this property. It exceeded our expectations in every way, and we would highly recommend it to anyone looking for a luxurious and memorable stay.",
  "Our stay at this property was simply outstanding. From the moment we arrived, we were treated like royalty. The staff anticipated our every need and made us feel incredibly welcome.",
  "The property's historical charm combined with modern amenities created a truly unique and memorable experience. It felt like stepping back in time while still enjoying all the comforts of the present day.",
  "We were blown away by the stunning architecture and landscaping of the hotel grounds. It was a pleasure to explore the gardens and admire the beauty of the surroundings.",
  "The culinary experience at the onsite restaurant was exceptional. Each dish was expertly prepared and presented, making every meal a delight for the senses.",
  "We appreciated the thoughtful gestures throughout our stay, such as the nightly turndown service and the complimentary refreshments in the lobby. It's these small touches that set this property apart.",
  "The attention to accessibility was commendable. As a wheelchair user, I found the property to be incredibly accommodating, with accessible rooms and facilities that made my stay comfortable and enjoyable.",
  "We were impressed by the hotel's commitment to supporting local artisans and businesses. It was evident in the decor, the amenities, and the overall ethos of the property.",
  "The family-friendly atmosphere of the hotel made our stay with young children stress-free and enjoyable. There were plenty of activities and amenities to keep them entertained, allowing us to relax and unwind.",
  "The sunset views from the rooftop bar were breathtaking. It was the perfect spot to enjoy a cocktail and watch the sun dip below the horizon.",
  "Overall, our experience at this property exceeded our expectations in every way. From the warm hospitality to the attention to detail, it was a stay we will never forget.",
  "Our recent stay at this property was nothing short of spectacular. The attention to detail in every aspect of the hotel, from the lobby to the guest rooms, was impeccable.",
  "We were greeted with a warm welcome upon arrival, and the staff made sure to personalize our experience throughout our stay. It truly felt like they went above and beyond to make us feel special.",
  "The hotel's commitment to sustainability was evident in their practices, from the use of eco-friendly toiletries to their efforts to minimize waste. It's refreshing to see a property that cares about the environment.",
  "We were delighted by the variety of activities available onsite. From cooking classes to yoga sessions, there was something for everyone to enjoy. It made our stay even more memorable.",
  "The hotel's location was perfect for exploring the surrounding area. We were able to easily visit nearby attractions and return to the comfort of our hotel at the end of the day.",
  "We were impressed by the level of cleanliness throughout the property. It was evident that cleanliness and hygiene were top priorities for the staff.",
  "The hotel's concierge service was invaluable in helping us plan our activities and excursions. Their recommendations were spot-on and enhanced our overall experience.",
  "The attention to detail in the design of the guest rooms was remarkable. Every element, from the furnishings to the artwork, contributed to a sense of luxury and comfort.",
  "Overall, our stay at this property exceeded our expectations. It was the perfect blend of luxury, comfort, and personalized service, and we can't wait to return.",
  "Our stay at this property was absolutely delightful. The staff were incredibly friendly and helpful, and the level of service was exceptional.",
  "The hotel's decor was stunning, with elegant furnishings and beautiful artwork throughout. It provided a luxurious ambiance that made our stay feel truly special.",
  "We were impressed by the range of dining options available onsite. From casual cafes to fine dining restaurants, there was something to suit every taste and occasion.",
  "The hotel's rooftop pool offered breathtaking views of the city skyline. It was the perfect place to relax and unwind after a day of exploring.",
  "We appreciated the hotel's commitment to inclusivity and diversity. It was evident in their hiring practices and the welcoming atmosphere they fostered for all guests.",
  "The attention to guest comfort was evident in every aspect of our stay, from the plush bedding to the thoughtful amenities provided in the room.",
  "The hotel's location was ideal for exploring the local area. We were within walking distance of shops, restaurants, and attractions, making it easy to explore on foot.",
  "The hotel's commitment to sustainability was commendable. We were pleased to see initiatives such as recycling programs and energy-efficient practices in place throughout the property.",
  "Overall, our experience at this property was exceptional. It was the perfect blend of luxury, comfort, and convenience, and we would highly recommend it to others.",
  "Our recent stay at this property was truly memorable. The staff went out of their way to ensure that every aspect of our visit was perfect, from check-in to check-out.",
  "The hotel's attention to detail was evident in every corner, from the lobby decor to the carefully curated amenities in the guest rooms. It was clear that no detail was overlooked.",
  "We were blown away by the culinary offerings at the hotel's restaurant. Each dish was a work of art, and the flavors were simply divine. It was a culinary experience we won't soon forget.",
  "The hotel's location was perfect for exploring the city. We were within walking distance of many attractions and landmarks, making it easy to immerse ourselves in the local culture.",
  "The hotel's commitment to sustainability was commendable. We appreciated the eco-friendly practices, such as the use of renewable energy and biodegradable toiletries.",
  "We were impressed by the level of cleanliness and hygiene maintained throughout the property. It was evident that the staff took great care to ensure a safe and comfortable environment for guests.",
  "The hotel's concierge service was incredibly helpful in arranging tours and activities during our stay. Their recommendations were spot-on and enhanced our overall experience.",
  "The hotel's commitment to providing exceptional service was evident in every interaction with the staff. They were attentive, friendly, and always willing to go the extra mile to ensure our satisfaction.",
  "Overall, our stay at this property exceeded our expectations in every way. It was the perfect combination of luxury, convenience, and hospitality, and we can't wait to return.",
  "Our stay at this property was nothing short of perfect. The staff were incredibly attentive and went above and beyond to ensure that we had everything we needed for a comfortable stay.",
  "The hotel's design seamlessly blended modern aesthetics with traditional elements, creating a truly unique and inviting atmosphere. It was a pleasure to explore the different spaces within the property.",
  "We were impressed by the variety of recreational activities available onsite. From tennis courts to a golf course, there was no shortage of ways to stay active and entertained during our stay.",
  "The hotel's commitment to sustainability was evident in their efforts to reduce waste and minimize their environmental impact. It was refreshing to see a property that prioritized eco-friendly practices.",
  "We were delighted by the culinary offerings at the hotel's restaurants. Each meal was expertly prepared and presented, and the service was attentive without being intrusive.",
  "The hotel's location was ideal for exploring the surrounding area. We were able to easily visit nearby attractions and return to the comfort of our hotel at the end of the day.",
  "We were impressed by the level of attention to detail in the guest rooms. From the luxurious bedding to the thoughtful amenities, every aspect of our stay was carefully curated for maximum comfort.",
  "The hotel's commitment to providing exceptional service was evident in every interaction with the staff. They were friendly, professional, and always willing to assist with any request.",
  "Overall, our experience at this property was outstanding. It exceeded our expectations in every way, and we look forward to returning for another visit in the future.",
  "Our stay at this property was simply phenomenal. From the moment we arrived, we were greeted with warmth and hospitality. The staff made us feel like VIPs throughout our entire visit.",
  "The hotel's architecture was stunning, with beautiful design elements that reflected the local culture. It was a pleasure to explore the property and discover its hidden gems.",
  "The hotel's commitment to sustainability was commendable. We appreciated their efforts to minimize their environmental footprint and support local conservation initiatives.",
  "We were blown away by the culinary experience at the hotel's restaurant. Each dish was a masterpiece, crafted with the finest ingredients and served with impeccable attention to detail.",
  "The hotel's location was perfect for exploring the surrounding area. We were able to easily visit nearby attractions and return to the comfort of our hotel at the end of the day.",
  "We were impressed by the cleanliness and hygiene standards maintained throughout the property. It was clear that the staff took pride in ensuring a safe and sanitary environment for guests.",
  "The hotel's concierge service was exceptional. They were knowledgeable, efficient, and always ready to assist with recommendations and reservations.",
  "Overall, our experience at this property was nothing short of extraordinary. It was the perfect blend of luxury, comfort, and hospitality, and we can't wait to return for another visit.",
  "The rooms at this property were spacious, elegantly decorated, and equipped with all the modern amenities we could ask for. It was a joy to return to such a comfortable and inviting space after a day of exploring.",
  "We were impressed by the attention to detail in the design of the rooms. From the luxurious bedding to the stylish furnishings, every element was carefully curated to create a serene and welcoming atmosphere.",
  "The hotel's commitment to guest comfort was evident in the thoughtful amenities provided in the rooms. We appreciated the little touches, like the plush bathrobes and premium toiletries, that made our stay feel extra special.",
  "We stayed in a suite during our visit, and it exceeded our expectations in every way. The extra space and added luxuries made our stay truly unforgettable.",
  "The rooms offered stunning views of the surrounding landscape, providing the perfect backdrop for a relaxing and rejuvenating stay. It was a treat to wake up to such breathtaking scenery every morning.",
  "We were impressed by the level of soundproofing in the rooms. Despite the hotel's central location, we enjoyed a peaceful and restful night's sleep every night.",
  "The hotel offered a variety of room options to suit every preference and budget. Whether you're looking for a cozy retreat or a spacious suite, there's something for everyone at this property.",
  "The rooms were impeccably clean and well-maintained, creating a comfortable and hygienic environment for guests. It was clear that the staff took great pride in ensuring the highest standards of cleanliness.",
  "We were delighted by the in-room technology available at this property. From smart TVs to high-speed internet access, everything we needed for a convenient and connected stay was right at our fingertips.",
  "Overall, the rooms at this property were a highlight of our stay. With their luxurious amenities, stunning views, and attention to detail, they provided the perfect sanctuary for a relaxing and memorable vacation.",
  "Our room at this property was like a dream come true. The elegant decor and cozy ambiance made us feel right at home from the moment we stepped inside.",
  "We were impressed by the functionality of the room layout. Every space was utilized efficiently, providing ample storage and a comfortable living area.",
  "The bed was incredibly comfortable, with soft linens and plush pillows that made for a restful night's sleep. We woke up feeling refreshed and rejuvenated each morning.",
  "The attention to detail in the room design was remarkable. From the tasteful artwork to the soothing color scheme, every element contributed to a relaxing and enjoyable stay.",
  "We appreciated the variety of room amenities provided, from the mini-fridge stocked with refreshments to the in-room coffee maker for our morning caffeine fix.",
  "The bathroom was a highlight of our room experience. The spacious shower and luxurious bathtub provided the perfect place to unwind after a long day of sightseeing.",
  "We were delighted by the stunning views from our room window. Whether it was a bustling cityscape or a tranquil garden view, it added an extra layer of enjoyment to our stay.",
  "The room service was prompt and efficient, allowing us to enjoy delicious meals in the comfort of our own room. It was a convenient option for lazy mornings or late-night cravings.",
  "The room was impeccably clean and well-maintained throughout our stay. It was clear that the housekeeping staff took pride in their work and ensured that every corner was spotless.",
  "Overall, the room exceeded our expectations in every way. With its comfort, functionality, and attention to detail, it truly felt like a home away from home.",
  "The surrounding environment of this property was simply breathtaking. Nestled amidst lush greenery and towering mountains, it offered a peaceful retreat from the hustle and bustle of city life.",
  "We were impressed by the abundance of outdoor activities available in the surrounding area. From hiking trails to water sports, there was no shortage of ways to explore and enjoy nature.",
  "The property's proximity to local attractions and landmarks made it the perfect home base for our adventures. We were able to easily visit nearby sights and return to the comfort of our hotel at the end of the day.",
  "We loved taking leisurely strolls around the neighborhood and soaking in the local culture. The charming streets, quaint cafes, and bustling markets added to the overall charm of our stay.",
  "The property's serene location provided the perfect backdrop for relaxation and rejuvenation. Whether we were lounging by the pool or enjoying a picnic in the park, it was easy to unwind and recharge.",
  "We were delighted by the variety of wildlife that called the surrounding area home. From colorful birds to playful monkeys, each encounter added to the magic of our stay.",
  "The property's commitment to sustainability extended beyond its walls and into the surrounding environment. We appreciated their efforts to preserve and protect the natural beauty of the area.",
  "The surrounding landscape offered breathtaking views at every turn. Whether it was a sunrise over the mountains or a sunset over the ocean, each vista was more stunning than the last.",
  "We were impressed by the sense of tranquility that permeated the surrounding environment. It was a welcome escape from the chaos of everyday life and allowed us to truly disconnect and unwind.",
  "Overall, the surrounding environment of this property added an extra layer of magic to our stay. With its natural beauty, outdoor activities, and sense of tranquility, it provided the perfect setting for a memorable vacation.",
  "The staff at this property were incredibly kind and attentive throughout our entire stay. From the front desk to the housekeeping team, everyone went out of their way to ensure we had a memorable experience.",
  "We were touched by the genuine warmth and hospitality of the staff at this hotel. They greeted us with smiles every day and took the time to get to know us personally, making us feel like part of the family.",
  "The kindness of the staff at this property truly made our stay special. Whether it was a thoughtful gesture or a simple act of kindness, they went above and beyond to ensure our comfort and happiness.",
  "We were impressed by the level of care and compassion shown by the staff at this hotel. They anticipated our needs before we even had to ask and went out of their way to make sure we had everything we needed.",
  "The staff's kindness extended beyond their professional duties and into genuine human connection. They took the time to listen to our stories, share their own experiences, and make us feel valued and appreciated as guests.",
  "We were moved by the generosity and kindness of the staff at this property. Whether it was a complimentary upgrade or a small token of appreciation, their gestures made our stay even more memorable.",
  "The staff's positive attitude and kind demeanor were infectious, creating a welcoming and inclusive atmosphere for all guests. It was clear that they genuinely cared about making our stay as enjoyable as possible.",
  "The kindness and compassion shown by the staff at this hotel set a shining example of hospitality. They treated every guest with respect and dignity, regardless of their background or circumstances.",
  "We were grateful for the kindness and support of the staff during a difficult time in our lives. Their empathy and understanding helped us feel comforted and cared for during our stay.",
  "Overall, the kindness of the staff at this property made our experience truly unforgettable. Their genuine care and compassion set the standard for exceptional service and hospitality.",
  "The staff at this property went above and beyond to make us feel welcome and valued during our stay. Their kindness and generosity left a lasting impression on us and made our vacation truly special.",
  "We were amazed by the level of personalized service provided by the staff at this hotel. From remembering our names to anticipating our preferences, they made us feel like VIPs from the moment we arrived.",
  "The staff's genuine concern for our well-being was evident in every interaction we had with them. They took the time to ensure that we were comfortable and had everything we needed to enjoy our stay.",
  "We were touched by the random acts of kindness we experienced during our time at this property. Whether it was a complimentary dessert or a heartfelt note, the staff's thoughtfulness made us feel appreciated and cared for.",
  "The kindness and compassion shown by the staff extended to all guests, creating a warm and welcoming atmosphere throughout the property. It was clear that they genuinely enjoyed making people happy.",
  "We were impressed by the staff's willingness to go the extra mile to accommodate our requests and make our stay as enjoyable as possible. Their dedication to customer satisfaction was truly commendable.",
  "The staff's positive attitude and friendly demeanor made us feel like part of the family during our stay. We enjoyed chatting with them and getting to know more about the local culture and traditions.",
  "The kindness of the staff at this property made us feel valued and appreciated as guests. It was refreshing to encounter such genuine hospitality in a world that often feels rushed and impersonal.",
  "We were blown away by the staff's attention to detail and commitment to making our stay memorable. Whether it was arranging a special celebration or providing insider tips on local attractions, they went above and beyond to exceed our expectations.",
  "Overall, the kindness and hospitality of the staff at this property set it apart from other hotels we've stayed at. Their genuine care and dedication made our experience truly unforgettable.",
  "The staff at this property epitomized kindness and professionalism throughout our stay. From the moment we checked in to the moment we left, their genuine warmth and helpfulness made us feel right at home.",
  "We were deeply touched by the staff's compassion and understanding during a challenging time in our lives. They went out of their way to offer support and comfort, and we are forever grateful for their kindness.",
  "The staff's commitment to making every guest feel valued and appreciated was evident in their interactions with us. They took the time to listen to our needs and preferences, ensuring that our stay was tailored to perfection.",
  "We were pleasantly surprised by the staff's thoughtfulness in anticipating our needs. From offering restaurant recommendations to providing extra amenities in our room, they went above and beyond to ensure our comfort and satisfaction.",
  "The kindness and generosity of the staff at this property left a lasting impression on us. Their genuine smiles and friendly greetings brightened our days and made us feel truly welcomed.",
  "We were impressed by the staff's dedication to creating a positive and inclusive environment for all guests. They treated everyone with respect and dignity, regardless of background or circumstance.",
  "The staff's willingness to accommodate our requests with grace and efficiency was truly remarkable. They handled every situation with professionalism and courtesy, making us feel valued and respected throughout our stay.",
  "We were moved by the staff's genuine concern for our well-being and happiness. They went out of their way to ensure that we had everything we needed to enjoy our stay to the fullest.",
  "The staff's genuine joy in their work was infectious, creating a warm and inviting atmosphere throughout the property. It was clear that they took pride in providing exceptional service to every guest.",
  "Overall, the kindness and hospitality of the staff at this property surpassed our expectations. Their genuine care and dedication made our stay truly memorable, and we can't wait to return.",
  "The staff at this property went out of their way to ensure that our stay was not just comfortable, but also memorable. Their genuine kindness and attentiveness made all the difference.",
  "We were touched by the staff's genuine interest in our well-being. They took the time to check in with us regularly and were always available to assist with any requests or questions we had.",
  "The staff's dedication to creating a welcoming and inclusive environment was evident in their interactions with guests from all walks of life. It was heartwarming to see everyone treated with the same level of respect and kindness.",
  "We were impressed by the staff's commitment to making our anniversary celebration extra special. From surprising us with a cake to arranging a romantic dinner, their thoughtful gestures made our day truly unforgettable.",
  "The staff's kindness extended beyond the walls of the property and into the local community. They actively supported local charities and initiatives, making a positive impact beyond their role as hoteliers.",
  "We were blown away by the staff's professionalism and efficiency in handling a minor issue during our stay. They resolved the issue promptly and went above and beyond to ensure that we were satisfied with the outcome.",
  "The staff's genuine passion for hospitality shone through in every interaction we had with them. Their enthusiasm and positivity made us feel like valued guests, and we left with fond memories of our time at the property.",
  "We were touched by the staff's thoughtfulness in remembering our preferences and anticipating our needs. It was the little touches, like our favorite newspaper waiting for us each morning, that made our stay truly special.",
  "The staff's kindness and generosity towards our children made our family vacation even more enjoyable. From providing coloring books to organizing fun activities, they went out of their way to ensure that everyone had a great time.",
  "Overall, the staff at this property set a shining example of hospitality and kindness. Their genuine care and dedication to making every guest feel welcome made our stay truly exceptional.",
  "The staff at this property demonstrated a level of kindness and hospitality that exceeded our expectations. Their genuine care for guests' well-being was evident in every interaction, making us feel truly valued and appreciated.",
  "We were deeply touched by the staff's compassion and empathy during a challenging situation. They went above and beyond to offer support and assistance, showing true human kindness that made a significant difference in our stay.",
  "The staff's positive attitude and cheerful demeanor created a warm and welcoming atmosphere throughout our entire visit. Their genuine smiles and friendly gestures made us feel like part of a big family, fostering a sense of belonging and happiness.",
  "We were impressed by the staff's proactive approach to ensuring our comfort and satisfaction. They anticipated our needs before we even had to ask, demonstrating a level of attentiveness and care that truly set them apart.",
  "The kindness and generosity of the staff at this property left a lasting impression on us. Their genuine willingness to go the extra mile to accommodate our requests and make our stay special made all the difference.",
  "We were moved by the staff's genuine concern for our happiness and well-being. They took the time to listen to our preferences and preferences, making personalized recommendations and arrangements that enhanced our overall experience.",
  "The staff's dedication to providing exceptional service was evident in every aspect of our stay. They consistently went above and beyond to ensure that we had everything we needed and more, leaving no detail overlooked.",
  "We were touched by the staff's thoughtfulness in creating memorable moments for us during our stay. From surprise treats to handwritten notes, their small gestures of kindness made our visit truly unforgettable.",
  "The staff's genuine passion for hospitality was evident in their enthusiastic and energetic demeanor. Their positive attitude and willingness to help made us feel valued and appreciated as guests, creating a delightful and memorable experience.",
  "Overall, the staff at this property exemplified the true meaning of hospitality. Their genuine kindness, compassion, and dedication to guest satisfaction made our stay an absolute pleasure, and we can't wait to return.",
];

export const usernames = [
  "Mitra908",
  "Narinder",
  "Shishir",
  "Raghunatha",
  "Gavit",
  "Archana",
  "Nagendra",
  "Mitali",
  "Anjali",
  "Prakash",
  "Suman",
  "Aarav",
  "Meena",
  "Sanjay",
  "Vidya",
  "Rohan",
  "Amita",
  "Vivek",
  "Priya",
  "Rajesh",
  "Deepa",
  "Kiran",
  "Varun",
  "Ananya",
  "Rajiv",
  "Sneha",
  "Vikram",
  "Anushka",
  "Arun",
  "Pooja",
  "Siddharth",
  "Swati",
  "Aarushi",
  "Rahul",
  "Anika",
  "Rajendra",
  "Sakshi",
  "Aryan",
  "Juhi",
  "Manish",
  "Tanvi",
  "Kunal",
  "Shreya",
  "Rohit",
  "Neha",
  "Vijay",
  "Meera",
  "Alok",
  "Mitali2330",
  "Alok19",
  "Riya678",
  "Karan123",
  "Preeti456",
  "Rohini789",
  "Rajat567",
  "Sonia321",
  "Vikas789",
  "Divya234",
  "Amit567",
  "Nisha890",
  "Ravi345",
  "Sonam678",
  "Gaurav123",
  "Sneha456",
  "Riya786",
  "Kunal999",
  "Anushka555",
  "Varun333",
  "Neha222",
  "Siddharth777",
  "Priya111",
  "Rajesh888",
  "Aarav444",
  "Pooja666",
  "Aryan888",
  "Shreya555",
  "Rahul333",
  "Juhi777",
  "Manish222",
  "Tanvi111",
  "Lily123",
  "Max456",
  "Sophie789",
  "Leo321",
  "Emma654",
  "Oliver987",
  "Grace234",
  "Henry567",
  "Zoe890",
  "Lucas123",
  "Ava456",
  "Ethan789",
  "Chloe321",
  "Mia654",
  "Liam987",
  "Ella234",
  "Alok19",
  "Riya678",
  "Karan123",
  "Preeti456",
  "Rohini789",
  "Rajat567",
  "Sonia321",
  "Vikas789",
  "Divya234",
  "Amit567",
  "Nisha890",
  "Ravi345",
  "Sonam678",
  "Gaurav123",
  "Sneha456",
  "Sakshi342",
  "Varun901",
  "Ananya675",
  "Rahul238",
  "Juhi459",
  "Manish832",
  "Tanvi501",
  "Kunal203",
  "Shreya702",
  "Rohit589",
  "Neha916",
  "Vijay745",
  "Meera307",
  "Alok843",
  "Anika129",
  "Rajendra576",
  "Sakshi843",
  "Aryan620",
  "Juhi718",
  "Manish564",
  "Tanvi290",
  "Kunal508",
  "Shreya999",
  "Rohit746",
  "Neha123",
  "Vijay432",
  "Meera876",
  "Alok912",
  "Anika345",
  "Rajendra789",
  "Sakshi123",
  "Aryan890",
  "Juhi567",
  "Manish234",
  "Tanvi901",
  "Kunal678",
  "Shreya345",
  "Rohit123",
  "Neha890",
  "Vijay456",
  "Meera123",
  "Alok789",
  "Anika456",
  "Rajendra234",
  "Sakshi567",
  "Aryan890",
  "Juhi123",
  "Manish456",
  "Tanvi789",
  "Kunal234",
  "Shreya567",
  "Rohit890",
  "Neha123",
  "Vijay456",
  "Meera789",
  "Alok234",
  "Anika567",
  "Rajendra890",
  "Sakshi123",
  "Aryan456",
  "Juhi789",
  "Manish234",
  "Tanvi567",
  "Kunal890",
  "Shreya123",
  "Rohit456",
  "Neha789",
  "Vijay234",
  "Meera567",
  "Alok890",
  "Anika123",
  "Rajendra456",
  "Sakshi789",
  "Aryan234",
  "Juhi567",
  "Manish890",
  "Tanvi123",
  "Kunal456",
  "Shreya789",
  "Rohit234",
  "Neha567",
  "Vijay890",
  "Meera123",
  "Alok456",
  "Anika789",
  "Rajendra234",
  "Sakshi567",
  "Aryan890",
  "Juhi123",
  "Manish456",
  "Tanvi789",
  "Kunal234",
  "Shreya567",
  "Rohit890",
  "Neha123",
  "Vijay456",
  "Meera789",
  "Alok234",
  "Anika567",
  "Rajendra890",
  "Sakshi123",
  "Aryan456",
  "Juhi789",
  "Manish234",
  "Tanvi567",
  "Kunal890",
  "Shreya123",
  "Rohit456",
  "Neha789",
  "Vijay234",
  "Meera567",
  "Alok890",
  "Anika123",
  "Rajendra456",
  "Sakshi789",
  "Aryan234",
  "Juhi567",
  "Manish890",
  "Tanvi123",
  "Kunal456",
  "Shreya789",
  "Rohit234",
  "Neha567",
  "Vijay890",
  "Meera123",
  "Alok456",
  "Anika789",
  "Rajendra234",
  "Sakshi567",
  "Aryan890",
  "Juhi123",
  "Manish456",
  "Tanvi789",
  "Kunal234",
  "Shreya567",
  "Rohit890",
  "Neha123",
  "Vijay456",
  "Meera789",
  "Alok234",
  "Anika567",
  "Rajendra890",
  "Sakshi123",
  "Aryan456",
  "Juhi789",
  "Manish234",
  "Tanvi567",
  "Kunal890",
  "Shreya123",
  "Rohit456",
  "Neha789",
  "Vijay234",
  "Meera567",
  "Alok890",
  "Anika123",
  "Rajendra456",
  "Sakshi789",
  "Aryan234",
  "Juhi567",
  "Manish890",
  "Tanvi123",
  "Kunal456",
  "Shreya789",
  "Rohit234",
  "Neha567",
  "Vijay890",
  "Meera123",
  "Alok456",
  "Anika789",
  "Rajendra234",
  "Sakshi567",
  "Aryan890",
  "Juhi123",
  "Manish456",
  "Tanvi789",
  "Kunal234",
  "Shreya567",
  "Rohit890",
  "Neha123",
  "Vijay456",
  "Meera789",
  "Alok234",
  "Anika567",
  "Rajendra890",
  "Sakshi123",
  "Aryan456",
  "Juhi789",
  "Manish234",
  "Tanvi567",
  "Kunal890",
  "Shreya123",
  "Rohit456",
  "Neha789",
  "Vijay234",
  "Meera567",
  "Alok890",
  "Anika123",
  "Rajendra456",
  "Sakshi789",
  "Aryan234",
  "Juhi567",
  "Manish890",
  "Tanvi123",
  "Kunal456",
  "Shreya789",
  "Rohit234",
  "Neha567",
  "Vijay890",
  "Meera123",
  "Alok456",
  "Anika789",
  "Rajendra234",
  "Sakshi567",
  "Aryan890",
  "Juhi123",
  "Manish456",
  "Tanvi789",
  "Kunal234",
  "Shreya567",
  "Rohit890",
  "Neha123",
  "Vijay456",
  "Meera789",
  "Alok234",
  "Anika567",
  "Rajendra890",
  "Sakshi123",
  "Aryan456",
  "Juhi789",
  "Manish234",
  "Tanvi567",
  "Kunal890",
  "Shreya123",
  "Rohit456",
  "Neha789",
  "Vijay234",
  "Meera567",
  "Alok890",
  "Anika123",
  "Rajendra456",
  "Sakshi789",
  "Aryan234",
  "Juhi567",
  "Manish890",
  "Tanvi123",
  "Kunal456",
  "Shreya789",
  "Rohit234",
  "Neha567",
  "Vijay890",
  "Meera123",
  "Alok456",
  "Anika789",
  "Rajendra234",
  "Sakshi567",
  "Aryan890",
  "Juhi123",
  "Manish456",
  "Tanvi789",
  "Kunal234",
  "Shreya567",
  "Rohit890",
  "Neha123",
  "Vijay456",
  "Meera789",
  "Alok234",
  "Anika567",
  "Rajendra890",
  "Sakshi123",
  "Aryan456",
  "Juhi789",
  "Manish234",
  "Tanvi567",
  "Kunal890",
  "Shreya123",
  "Rohit456",
  "Neha789",
  "Vijay234",
  "Meera567",
  "Alok890",
  "Anika123",
  "Rajendra456",
  "Sakshi789",
  "Aryan234",
  "Juhi567",
  "Manish890",
  "Tanvi123",
  "Kunal456",
  "Shreya789",
  "Rohit234",
];


export const platform = [
  "Google", "airbnb", "makemytrip"
]